#!/bin/bash

echo "Enter user name"
read user name
git config --global user.name "$user name"
echo "Enter user email"
read user email
git config --global user.email "$email"
echo "Enter user password"
read user password
git config --global user.password "$user password"
